# Generated by Django 5.1.7 on 2025-05-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_testcase_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(blank=True, help_text='Входные данные для тестирования', null=True),
        ),
    ]
