# Generated by Django 5.1.7 on 2025-04-18 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')],
                        max_length=50,
                    ),
                ),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                (
                    'problem',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problem.problem'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='submissions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Submissions',
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
