# Generated by Django 5.1.7 on 2025-05-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
