# Generated by Django 5.1.7 on 2025-05-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submission_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='language',
            new_name='programming_language',
        ),
    ]
