# Generated by Django 5.1.7 on 2025-04-18 22:53

import django.db.models.deletion
import file_storage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=file_storage.models.course_directory_path)),
                (
                    'file_type',
                    models.CharField(
                        choices=[
                            ('document', 'Document'),
                            ('video', 'Video'),
                            ('image', 'Image'),
                            ('audio', 'Audio'),
                            ('archive', 'Archive'),
                            ('other', 'Other'),
                        ],
                        max_length=20,
                    ),
                ),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                (
                    'course',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course.course'
                    ),
                ),
                (
                    'uploaded_by',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
