# Generated by Django 5.1.7 on 2025-05-15 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='partisipants',
            field=models.ManyToManyField(related_name='competitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
